buildscript {
    repositories {
        // mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'Maven Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'

            content {
                includeGroupAndSubgroups 'org.graceframework'
            }
            mavenContent {
                snapshotsOnly()
            }
        }
    }
    dependencies {
        classpath "org.graceframework:grace-gradle-plugin:$graceVersion"
        classpath "io.github.gradle-nexus:publish-plugin:2.0.0"
    }
}

logger.lifecycle "GORM VERSION = ${project.datastoreVersion}"

group = "org.graceframework"
version = project.projectVersion

ext {
    isCiBuild = project.hasProperty("isCiBuild") || System.getenv().get("CI") as Boolean
    isBuildSnapshot = project.version.endsWith("-SNAPSHOT")
    isReleaseVersion = !isBuildSnapshot
}

ext."signing.keyId" = System.getenv("SIGNING_KEY") ?: project.hasProperty("signing.keyId") ? project.getProperty('signing.keyId') : null
ext."signing.password" = System.getenv("SIGNING_PASSPHRASE") ?: project.hasProperty("signing.password") ? project.getProperty('signing.password') : null
ext."signing.secretKeyRingFile" = project.hasProperty("signing.secretKeyRingFile") ? project.getProperty('signing.secretKeyRingFile') : null

apply plugin: 'groovy'
apply plugin: 'maven-publish'
apply plugin: "io.github.gradle-nexus.publish-plugin"
apply plugin: 'org.graceframework.grace-doc'

nexusPublishing {
    repositories {
        sonatype {
            def mavenUser = System.getenv("MAVEN_CENTRAL_USER") ?: project.hasProperty("mavenCentralUsername") ? project.mavenCentralUsername : ''
            def mavenPass = System.getenv("MAVEN_CENTRAL_PASSWORD") ?: project.hasProperty("mavenCentralPassword") ? project.mavenCentralPassword : ''
            nexusUrl = uri("https://ossrh-staging-api.central.sonatype.com/service/local/")
            snapshotRepositoryUrl = uri("https://central.sonatype.com/repository/maven-snapshots/")
            username = mavenUser
            password = mavenPass
        }
    }
}

allprojects {
    ext {
        groovyVersion = System.getenv('CI_GROOVY_VERSION') ?: project.groovyVersion
    }

    repositories {
        mavenCentral()
        maven {
            name = 'Maven Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'

            content {
                includeGroupAndSubgroups 'org.graceframework'
            }
            mavenContent {
                snapshotsOnly()
            }
        }
    }

    configurations {
        documentation
    }

    dependencies {
        documentation "com.github.javaparser:javaparser-core:$javaParserCoreVersion"
        documentation "org.apache.groovy:groovy:$groovyVersion"
        documentation "org.apache.groovy:groovy-ant:$groovyVersion"
    }
}

subprojects { project ->
    if (project.name == 'docs') {
        return
    }

    apply plugin: 'groovy'
    apply plugin: "java-library"
    apply plugin: 'maven-publish'
    apply plugin: 'signing'
    apply plugin: "io.spring.dependency-management"

    sourceCompatibility = "17"
    targetCompatibility = "17"

    java {
        withJavadocJar()
        withSourcesJar()
    }

    dependencyManagement {
        imports {
            mavenBom "org.graceframework:grace-bom:$graceVersion"
        }
        applyMavenExclusions false
        generatedPomCustomization {
            enabled = false
        }
    }

    dependencies {
        api "org.apache.groovy:groovy"

        testImplementation "org.apache.groovy:groovy-json"
        testImplementation "org.apache.groovy:groovy-templates"
        testImplementation "org.apache.groovy:groovy-test-junit5", {
            exclude group: "org.junit.platform", module: "junit-platform-launcher"
            exclude group: "org.junit.jupiter", module: "junit-jupiter-engine"
        }
        testImplementation "org.spockframework:spock-core", {
            exclude group: "org.junit.platform", module: "junit-platform-engine"
        }
        testImplementation "org.junit.jupiter:junit-jupiter-api"
        testImplementation "org.junit.platform:junit-platform-runner"
        testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
    }

    publishing {
        publications {
            maven(MavenPublication) {
                def projectArtifactId = project.name
                def projectName = project.name.split('-')*.capitalize().join(' ')

                artifactId projectArtifactId
                from components.java

                versionMapping {
                    usage('java-api') {
                        fromResolutionOf('runtimeClasspath')
                    }
                    usage('java-runtime') {
                        fromResolutionResult()
                    }
                }

                pom {
                    name = projectName                
                    description = "Grace Data : $projectName"
                    url = 'https://github.com/graceframework/grace-data-mongodb'

                    licenses {
                        license {
                            name = 'The Apache Software License, Version 2.0'
                            url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                            distribution = 'repo'
                        }
                    }

                    scm {
                        url = 'https://github.com/graceframework/grace-data-mongodb'
                        connection = 'scm:git@github.com:graceframework/grace-data-mongodb.git'
                        developerConnection = 'scm:git@github.com:graceframework/grace-data-mongodb.git'
                    }

                    developers {
                        developer {
                            id = 'rainboyan'
                            name = 'Michael Yan'
                            email = 'rain@rainboyan.com'
                        }
                    }
                }
            }
        }
    }

    afterEvaluate {
        signing {
            required { isReleaseVersion }
            sign publishing.publications.maven
        }
    }

    tasks.withType(Sign) {
        onlyIf { isReleaseVersion }
    }

    //do not generate extra load on Nexus with new staging repository if signing fails
    tasks.withType(io.github.gradlenexus.publishplugin.InitializeNexusStagingRepository).configureEach {
        shouldRunAfter(tasks.withType(Sign))
    }
}


def cleanTask = project.tasks.findByName('clean')
if (cleanTask == null) {
    task clean(type: Delete) {
        delete(buildDir)
    }
}
else {
    cleanTask.doLast {
        ant.delete(dir: 'build/docs')
    }
}

tasks.withType(Groovydoc) {
    group = 'Documentation'
    docTitle = "Grace Data MongoDB - ${project.version}"
    destinationDir = project.file('build/docs/manual/api')
    def files = []
    project.rootProject.subprojects
            .findAll { !it.name != 'docs' && !it.name.startsWith('examples') }
            .each { subproject ->
                if(subproject.file('src/main/groovy').exists()) {
                    files += subproject.files('src/main/groovy')
                }
                if(subproject.file('src/main/java').exists()) {
                    files += subproject.files('src/main/java')
                }
            }
    if (project.file('src/main/groovy').exists()) {
        files += project.files('src/main/groovy')
    }
    source = files
    classpath += configurations.documentation
}

publishGuide {
    dependsOn groovydoc
    sourceDir = project.file('src/docs')
}

task docs {
    dependsOn groovydoc, publishGuide
}
