buildscript {
    repositories {
        // mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "org.graceframework:grace-gradle-plugin:$graceVersion"
        // classpath "org.graceframework.plugins:asset-pipeline-gradle:$assetPipelineVersion"
        classpath "com.github.erdi:webdriver-binaries-gradle-plugin:$webdriverBinariesVersion"
        classpath "org.graceframework.plugins:views-gradle:6.3.0-M1"
        classpath "io.github.gradle-nexus:publish-plugin:2.0.0"
    }
}

logger.lifecycle "GORM VERSION = ${project.datastoreVersion}"

group = "org.graceframework"
version = project.projectVersion

ext {
    isCiBuild = project.hasProperty("isCiBuild") || System.getenv().get("CI") as Boolean
    isBuildSnapshot = project.version.endsWith("-SNAPSHOT")
    isReleaseVersion = !isBuildSnapshot
    servletApiVersion = "6.0.0"
    nexusUsername = System.getenv("SONATYPE_USERNAME") ?: project.hasProperty("sonatypeOssUsername") ? project.sonatypeOssUsername : ''
    nexusPassword = System.getenv("SONATYPE_PASSWORD") ?: project.hasProperty("sonatypeOssPassword") ? project.sonatypeOssPassword : ''
}

ext."signing.keyId" = System.getenv("SIGNING_KEY") ?: project.hasProperty("signing.keyId") ? project.getProperty('signing.keyId') : null
ext."signing.password" = System.getenv("SIGNING_PASSPHRASE") ?: project.hasProperty("signing.password") ? project.getProperty('signing.password') : null
ext."signing.secretKeyRingFile" = project.hasProperty("signing.secretKeyRingFile") ? project.getProperty('signing.secretKeyRingFile') : null

apply plugin: 'groovy'
apply plugin: 'maven-publish'
apply plugin: "io.github.gradle-nexus.publish-plugin"
apply plugin: 'org.graceframework.grace-doc'

nexusPublishing {
    repositories {
        sonatype {
            def ossUser = System.getenv("SONATYPE_USERNAME") ?: project.hasProperty("sonatypeOssUsername") ? project.sonatypeOssUsername : ''
            def ossPass = System.getenv("SONATYPE_PASSWORD") ?: project.hasProperty("sonatypeOssPassword") ? project.sonatypeOssPassword : ''
            def ossStagingProfileId = System.getenv("SONATYPE_STAGING_PROFILE_ID") ?: project.hasProperty("sonatypeOssStagingProfileId") ? project.sonatypeOssStagingProfileId : ''
            nexusUrl = uri("https://s01.oss.sonatype.org/service/local/")
            snapshotRepositoryUrl = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
            username = ossUser
            password = ossPass
            stagingProfileId = ossStagingProfileId
        }
    }
}

allprojects {
    ext {
        groovyVersion = System.getenv('CI_GROOVY_VERSION') ?: project.groovyVersion
    }

    repositories {
        mavenCentral()
        if (project.projectVersion.endsWith('-SNAPSHOT')) {
            maven {
                name = 'Sonatype OSS Snapshot Repo'
                url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
            }
        }
    }

    configurations {
        documentation
    }

    dependencies {
        documentation "com.github.javaparser:javaparser-core:$javaParserCoreVersion"
        documentation "org.apache.groovy:groovy:$groovyVersion"
        documentation "org.apache.groovy:groovy-ant:$groovyVersion"
    }
}

subprojects { project ->
    if (project.name.startsWith("examples")) {
        group = "examples"

        apply plugin: 'groovy'

        if (project.name.contains('grace')) {
            apply plugin:"org.graceframework.grace-web"
            apply plugin:"org.graceframework.grace-gsp"
            // Execution failed for task ':examples-grace-hibernate5-mongodb:assetCompile'.
            // > java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void groovy.lang.IntRange.<init>(boolean, boolean, int, int)'
            // apply plugin: "org.graceframework.asset-pipeline"
        }

        boolean usesGeb = project.name.contains('grace-hibernate5-mongodb') || project.name.contains('grace-mongodb') || project.name.contains('grace-mongodb-database-per-tenant')|| project.name.contains('grace-rxmongodb')

        if (usesGeb) {
            apply plugin:"com.github.erdi.webdriver-binaries"
        }

        if (project.name == "examples-grace-test-data-service") {
            apply plugin:"org.graceframework.grace-web"
            apply plugin:"org.graceframework.plugins.views-json"
        }

        if (project.name == "examples-springboot-mongodb") {
            apply plugin: 'org.springframework.boot'
            apply plugin: 'io.spring.dependency-management'

            dependencyManagement {
                imports {
                    mavenBom "org.graceframework:grace-bom:$graceVersion"
                }
                applyMavenExclusions false
                generatedPomCustomization {
                    enabled = false
                }
            }
        }

        dependencies {
            testImplementation "org.hibernate.validator:hibernate-validator"
            testImplementation "org.apache.groovy:groovy-test-junit5"
            testImplementation "org.spockframework:spock-core", { transitive = false }
            testImplementation "org.junit.jupiter:junit-jupiter-api"
            testImplementation "org.junit.platform:junit-platform-runner"
            testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
        }

        tasks.withType(Test) {
            useJUnitPlatform()
            testLogging {
                showStandardStreams = true
                exceptionFormat = 'full'
            }
        }

        tasks.withType(Jar).configureEach {
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }

        return
    }

    boolean isPluginProject = project.name.startsWith("grace") && project.name.endsWith("-plugin")

    apply plugin: 'groovy'

    if (isPluginProject) {
        group = "org.graceframework.plugins"
        version = rootProject.version

        apply plugin: "org.graceframework.grace-plugin"
    }
    else {
        group = "org.graceframework"
        version = rootProject.version

        apply plugin: "io.spring.dependency-management"

        dependencyManagement {
            imports {
                mavenBom "org.graceframework:grace-bom:$graceVersion"
            }
            applyMavenExclusions false
            generatedPomCustomization {
                enabled = false
            }
        }
    }

    if (project.name == 'docs') {
        return
    }

    apply plugin: "java-library"
    apply plugin: 'maven-publish'
    apply plugin: 'signing'

    sourceCompatibility = "17"
    targetCompatibility = "17"

    java {
        withJavadocJar()
        withSourcesJar()
    }

    dependencies {
        api "org.apache.groovy:groovy"

        testImplementation "org.apache.groovy:groovy-json"
        testImplementation "org.apache.groovy:groovy-templates"
        testImplementation "org.apache.groovy:groovy-test-junit5", {
            exclude group: "org.junit.platform", module: "junit-platform-launcher"
            exclude group: "org.junit.jupiter", module: "junit-jupiter-engine"
        }
        testImplementation "org.spockframework:spock-core", {
            exclude group: "org.junit.platform", module: "junit-platform-engine"
        }
        testImplementation "org.junit.jupiter:junit-jupiter-api"
        testImplementation "org.junit.platform:junit-platform-runner"
        testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
    }

    publishing {
        publications {
            maven(MavenPublication) {
                def projectArtifactId = project.name
                def projectName = project.name.split('-')*.capitalize().join(' ')
                if (project.name == 'grace-plugin') {
                    projectArtifactId = 'mongodb'
                    projectName = 'Grace MongoDb Plugin'
                }

                artifactId projectArtifactId
                from components.java

                versionMapping {
                    usage('java-api') {
                        fromResolutionOf('runtimeClasspath')
                    }
                    usage('java-runtime') {
                        fromResolutionResult()
                    }
                }

                pom {
                    name = projectName                
                    description = "Grace Data : $projectName"
                    url = 'https://github.com/graceframework/grace-data-mongodb'

                    licenses {
                        license {
                            name = 'The Apache Software License, Version 2.0'
                            url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                            distribution = 'repo'
                        }
                    }

                    scm {
                        url = 'https://github.com/graceframework/grace-data-mongodb'
                        connection = 'scm:git@github.com:graceframework/grace-data-mongodb.git'
                        developerConnection = 'scm:git@github.com:graceframework/grace-data-mongodb.git'
                    }

                    developers {
                        developer {
                            id = 'rainboyan'
                            name = 'Michael Yan'
                            email = 'rain@rainboyan.com'
                        }
                    }
                }

                afterEvaluate {
                    if (isPluginProject) {
                        artifact source:"${sourceSets.main.groovy.classesDirectory.get()}/META-INF/grails-plugin.xml",
                                classifier:"plugin",
                                extension:'xml'
                    }
                }

            }
        }
    }

    afterEvaluate {
        signing {
            required { isReleaseVersion }
            sign publishing.publications.maven
        }
    }

    tasks.withType(Sign) {
        onlyIf { isReleaseVersion }
    }

    //do not generate extra load on Nexus with new staging repository if signing fails
    tasks.withType(io.github.gradlenexus.publishplugin.InitializeNexusStagingRepository).configureEach {
        shouldRunAfter(tasks.withType(Sign))
    }
}


def cleanTask = project.tasks.findByName('clean')
if (cleanTask == null) {
    task clean(type: Delete) {
        delete(buildDir)
    }
}
else {
    cleanTask.doLast {
        ant.delete(dir: 'build/docs')
    }
}

tasks.withType(Groovydoc) {
    group = 'Documentation'
    docTitle = "Grace Data MongoDB - ${project.version}"
    destinationDir = project.file('build/docs/manual/api')
    def files = []
    project.rootProject.subprojects
            .findAll { !it.name != 'docs' && !it.name.startsWith('examples') }
            .each { subproject ->
                if(subproject.file('src/main/groovy').exists()) {
                    files += subproject.files('src/main/groovy')
                }
                if(subproject.file('src/main/java').exists()) {
                    files += subproject.files('src/main/java')
                }
            }
    if (project.file('src/main/groovy').exists()) {
        files += project.files('src/main/groovy')
    }
    source = files
    classpath += configurations.documentation
}

docs {
    dependsOn groovydoc
    sourceDir = project.file('src/docs')
}
