projectVersion=2023.3.0-SNAPSHOT
assetPipelineVersion=6.3.0-M1
caffeineVersion=2.9.3
datastoreVersion=2023.3.0-M1
graceVersion=2023.3.0-M1
groovyVersion=4.0.24
jakartaElVersion=4.0.2
jakartaValidationVersion=3.0.2
h2Version=2.2.224
hibernateCoreVersion=5.6.15.Final
hibernatePluginVersion=2023.2.0
hibernateValidatorVersion=8.0.2.Final
jansiVersion=2.4.1
javaParserCoreVersion=3.25.10
junitJupiterVersion=5.10.2
mongodbDriverVersion=5.0.1
seleniumSafariDriverVersion=3.14.0
seleniumVersion=3.14.0
spockVersion=2.3-groovy-4.0
springBootVersion=3.3.7
springVersion=6.1.18
webdriverBinariesVersion=1.4
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1536M -XX:MaxMetaspaceSize=512M
