projectVersion=2024.0.0-SNAPSHOT
assetPipelineVersion=7.0.0-M1
datastoreVersion=2023.3.0
graceVersion=2024.0.0-M1
graceViewsVersion=6.3.0
groovyVersion=4.0.27
jakartaElVersion=4.0.2
jansiVersion=2.4.1
javaParserCoreVersion=3.26.4
mongodbDriverVersion=5.2.1
seleniumVersion=4.2.2
webdriverBinariesVersion=3.2

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1536M -XX:MaxMetaspaceSize=512M
