// core
include "grace-datastore-gorm-bson"
include "grace-datastore-gorm-mongodb"
include "grace-datastore-gorm-mongodb-ext"

// documentation
include 'docs'

// plugins
include 'grace-plugin'

// examples
include 'examples-grace-mongodb'
project(":examples-grace-mongodb").projectDir = new File(settingsDir, "examples/grace-mongodb")

include 'examples-grace-mongodb-database-per-tenant'
project(":examples-grace-mongodb-database-per-tenant").projectDir = new File(settingsDir, "examples/grace-mongodb-database-per-tenant")

include 'examples-grace-hibernate5-mongodb'
project(":examples-grace-hibernate5-mongodb").projectDir = new File(settingsDir, "examples/grace-hibernate5-mongodb")

include 'examples-springboot-mongodb'
project(":examples-springboot-mongodb").projectDir = new File(settingsDir, "examples/springboot-mongodb")

include 'examples-test-data-service'
project(":examples-test-data-service").projectDir = new File(settingsDir, "examples/test-data-service")
