==== Dependency Upgrades

Grace Data MongoDB {version} supports Apache Groovy 4.0, Java 17, MongoDB Driver 5.2 and Spring 6.2.x.

Each of these underlying components may have changes that require altering your application. These changes are beyond the scope of this documentation.

==== Default Autowire By Type inside GORM Data Services

A GORM Service (or a bean) inside GORM DataService will default to autowire by-type, For example:

_./app/services/example/BookService.groovy_
```
package example

import grails.gorm.services.Service

@Service(Book)
abstract class BookService {

    TestService testRepo

    abstract Book save(String title, String author)

    void doSomething() {
        assert testRepo != null
    }
}
```

Please note that with autowire by-type as the default, when multiple beans for same type are found the application with throw Exception. Use the Spring `@Qualifier annotation for link:{springrefdoc}/core/beans/annotation-config/autowired-qualifiers.html[Fine-tuning Annotation Based Autowiring with Qualifiers].
