dependencies {
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.graceframework:grace-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.graceframework:grace-plugin-codecs"
    implementation "org.graceframework:grace-plugin-services"
    implementation "org.graceframework:grace-plugin-datasource"
    implementation "org.graceframework:grace-boot"
    implementation "org.graceframework:grace-logging"
    implementation "org.graceframework:grace-plugin-cache"
    implementation "org.graceframework:grace-plugin-events"
    implementation project(":grace-plugin")
    implementation "org.graceframework:grace-views-json"
    // implementation "org.graceframework:grace-views-json-templates"
    // implementation 'org.graceframework.plugins:spring-security-core:4.0.3'
    // implementation 'org.graceframework.plugins:spring-security-rest:3.0.1'
    profile "org.graceframework.profiles:rest-api"
    testImplementation "org.graceframework:grails-test-support"
}
