buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:$springBootVersion")
    }
}

apply plugin: 'org.springframework.boot'

ext['groovy.version'] = "$groovyVersion"

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    implementation "org.mongodb:mongodb-driver-sync:$mongodbDriverVersion"
    implementation project(":grace-plugin")

    testImplementation"org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    testImplementation"org.spockframework:spock-core:$spockVersion"
}
