dependencies {
    api "org.springframework.boot:spring-boot-autoconfigure:$springBootVersion"
    api "org.apache.groovy:groovy:$groovyVersion"
    api project(":grails-datastore-gorm-mongodb")
    api project(":grails-datastore-gorm-mongodb-ext"), {
        exclude group:'org.graceframework', module:'grails-datastore-gorm-mongodb'
    }
    api "org.springframework:spring-tx:$springVersion"
}
